# Generated by Django 5.1.2 on 2024-10-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('EmailAddress', models.EmailField(max_length=250, null=True, unique=True)),
                ('Password', models.CharField(max_length=250)),
                ('Staff', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
