# Generated by Django 5.1.2 on 2024-10-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='EmailAddress',
            field=models.EmailField(default=False, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteusers',
            name='Staff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
